FROM ubuntu:bionic

# Install Java and Maven on the image
RUN apt-get update && apt-get install -y openjdk-8-jdk maven

# Copy the Quarkus app code from the Github repository to the image
COPY . /fax.med-united.health

# Copy the resources folder to the container so that resources are accessible
COPY src/main/resources src/main/resources

# Change the working directory to the root of the Quarkus app
WORKDIR /fax.med-united.health

# Build the Quarkus app
RUN mvn clean install

# Expose the port on which the Quarkus app runs
EXPOSE 8080

# Start the Quarkus app by running the jar file generated by the build process
CMD java -jar target/fax-1.0.0-SNAPSHOT-runner.jar
